{
 "title": "Travel",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Attempts By Hotel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (attempt_count) by (Hotel)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Attempts By Destination",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (attempt_count) by (Destinations)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Bookings By Hotel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (success_count) by (Hotel)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful Booking By Destination",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (success_count) by (Destinations)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}